### ISSUE TITLE
GetPlayers() + GetPlayerIDs() Not Working

### ISSUE THREAD

**Issue by alicepolice** [zMoooooritz/go-let-loose#1]
[rcon_player_cmd.go](https://github.com/zMoooooritz/go-let-loose/blob/master/pkg/rcon/rcon_player_cmd.go)

GetPlayers() + GetPlayerIDs() 

Not Working

**Comment by zMoooooritz** [comment]
Thanks for the report, this is indeed an oversight in the implementation (caused by the inconsistent naming of the hll api)

This will be resolved in the next release that is to come in the next days
