### ISSUE TITLE
In ParsePlayerInfo, the parsing of the player's name should preserve the case of the name.

### ISSUE THREAD

**Issue by alicepolice** [zMoooooritz/go-let-loose#5]
The error occurs when GetPlayerInfo is called again after retrieving hll.DetailedPlayerInfo through GetPlayerInfo. Since this command is case-sensitive regarding the player's name, it will result in an error.

There are two scenarios as follows:
1、Automatically disband infantry squads without a leader: After the first playerinfo retrieves all team information, players with uppercase letters in their names cannot be disbanded because their names were converted to lowercase.
2、Automatic team balancing at the start of the game: I designed a system to sort players by rank from highest to lowest, then assign them to teams one by one. This caused a timeout error when I called playerinfo for the second time.

rcon_player_cmd.go
```
split := strings.SplitN(line, ": ", 2)
if len(split) >= 2 {
	valueMap[strings.ToLower(split[0])] = strings.ToLower(split[1])
}
```
This part of the code should be modified as follows.
```
split := strings.SplitN(line, ": ", 2)
if len(split) >= 2 {
	if split[0] == "Name" {
		valueMap[strings.ToLower(split[0])] = split[1]
	} else {
		valueMap[strings.ToLower(split[0])] = strings.ToLower(split[1])
	}
}
```

I haven't encountered the issue of event callbacks being triggered multiple times yet. Thank you for your effort.

**Comment by zMoooooritz** [comment]
Hey, there
Thank you for the detailed bug report, with such information fixing those things is a blast (altough this should have been caught way earlier and is a stupid oversight)

Fixed in commit e5aebc2; The new release v0.0.8 that contains the bugfix should be available in the next minutes
